

def traduzir_saida(saida: str) -> str:
    for en, pt in TRANSLATE_MAP().items():
        saida = saida.replace(en, pt)
    return saida



def TRANSLATE_MAP():
	# Exemplo de dicionário
	return {
	"is not defined":"não está definido!",
	"errors": "erros",
	"warnings": "avisos",
	"failed": "falhou",
	"failure": "falha",
	"success": "sucesso",
	"successful": "bem-sucedido",
	"unknown": "desconhecido",
	"invalid": "inválido",
	"valid": "válido",
	"missing": "ausente",
	"found": "encontrado",
	"not found": "não encontrado",
	"empty": "vazio",
	"loaded": "carregado",
	"loading": "carregando",
	"unloaded": "descarregado",
	"started": "iniciado",
	"starting": "iniciando",
	"stopped": "parado",
	"stopping": "parando",
	"running": "em execução",
	"finished": "finalizado",
	"completed": "concluído",
	"aborted": "abortado",
	"cancelled": "cancelado",
	"denied": "negado",
	"refused": "recusado",
	"forbidden": "proibido",
	"allowed": "permitido",
	"available": "disponível",
	"unavailable": "indisponível",
	"supported": "suportado",
	"unsupported": "não suportado",
	"enabled": "ativado",
	"disabled": "desativado",
	"timeout": "tempo limite",
	"expired": "expirado",
	"retry": "tentar novamente",
	"retries": "tentativas",
	"limit": "limite",
	"exceeded": "excedido",
	"overridden": "sobrescrito",
	"default": "padrão",
	"custom": "personalizado",

	"file": "arquivo",
	"files": "arquivos",
	"folder": "pasta",
	"folders": "pastas",
	"directory": "diretório",
	"directories": "diretórios",
	"path": "caminho",
	"paths": "caminhos",
	"name": "nome",
	"names": "nomes",
	"extension": "extensão",
	"size": "tamanho",
	"sizes": "tamanhos",
	"modified": "modificado",
	"created": "criado",
	"deleted": "excluído",
	"remove": "remover",
	"removed": "removido",
	"rename": "renomear",
	"renamed": "renomeado",
	"copy": "copiar",
	"copied": "copiado",
	"move": "mover",
	"moved": "movido",
	"read": "ler",
	"write": "escrever",
	"written": "escrito",
	"execute": "executar",
	"executable": "executável",
	"append": "acrescentar",
	"open": "abrir",
	"opened": "aberto",
	"close": "fechar",
	"closed": "fechado",
	"save": "salvar",
	"saved": "salvo",
	"symlink": "link simbólico",
	"hardlink": "link físico",

	"permission": "permissão",
	"permissions": "permissões",
	"access": "acesso",
	"owner": "dono",
	"group": "grupo",
	"others": "outros",
	"read-only": "somente leitura",
	"read-write": "leitura e escrita",
	"locked": "bloqueado",
	"unlocked": "desbloqueado",
	"restricted": "restrito",
	"privileged": "com privilégios",
	"unprivileged": "sem privilégios",
	"admin": "admin",
	"administrator": "administrador",
	"root": "root",
	"user": "usuário",
	"users": "usuários",
	"guest": "convidado",
	"session": "sessão",
	"sessions": "sessões",
	"login": "login",
	"logout": "logout",
	"authenticated": "autenticado",
	"unauthenticated": "não autenticado",
	"authorized": "autorizado",
	"unauthorized": "não autorizado",
	"password": "senha",
	"username": "nome de usuário",
	"credentials": "credenciais",
	"key": "chave",
	"keys": "chaves",
	"certificate": "certificado",
	"certificates": "certificados",
	"signature": "assinatura",

	"connection": "conexão",
	"connections": "conexões",
	"connected": "conectado",
	"disconnected": "desconectado",
	"offline": "offline",
	"online": "online",
	"host": "host",
	"hosts": "hosts",
	"server": "servidor",
	"servers": "servidores",
	"client": "cliente",
	"clients": "clientes",
	"address": "endereço",
	"addresses": "endereços",
	"ip": "ip",
	"port": "porta",
	"ports": "portas",
	"protocol": "protocolo",
	"protocols": "protocolos",
	"request": "requisição",
	"requests": "requisições",
	"response": "resposta",
	"responses": "respostas",
	"status": "status",
	"latency": "latência",
	"bandwidth": "largura de banda",
	"throughput": "taxa de transferência",
	"packet": "pacote",
	"packets": "pacotes",
	"firewall": "firewall",
	"proxy": "proxy",
	"gateway": "gateway",
	"router": "roteador",
	"dns": "dns",
	"domain": "domínio",
	"ssl": "ssl",
	"tls": "tls",
	"handshake": "handshake",
	"timeouted": "expirado",
	"retrying": "re-tentando",

	"system": "sistema",
	"kernel": "kernel",
	"process": "processo",
	"processes": "processos",
	"thread": "thread",
	"threads": "threads",
	"service": "serviço",
	"services": "serviços",
	"signal": "sinal",
	"signals": "sinais",
	"cpu": "cpu",
	"memory": "memória",
	"ram": "ram",
	"swap": "swap",
	"disk": "disco",
	"disks": "discos",
	"volumes": "volumes",
	"partition": "partição",
	"partitions": "partições",
	"device": "dispositivo",
	"devices": "dispositivos",
	"driver": "driver",
	"drivers": "drivers",
	"hardware": "hardware",
	"software": "software",
	"resource": "recurso",
	"resources": "recursos",
	"limits": "limites",
	"architecture": "arquitetura",
	"platform": "plataforma",
	"environment": "ambiente",
	"variable": "variável",
	"variables": "variáveis",
	"locale": "localidade",
	"encoding": "codificação",
	"decoding": "decodificação",

	"python": "python",
	"module": "módulo",
	"modules": "módulos",
	"package": "pacote",
	"packages": "pacotes",
	"library": "biblioteca",
	"libraries": "bibliotecas",
	"script": "script",
	"scripts": "scripts",
	"function": "função",
	"functions": "funções",
	"class": "classe",
	"classes": "classes",
	"argument": "argumento",
	"arguments": "argumentos",
	"parameter": "parâmetro",
	"parameters": "parâmetros",
	"returns": "retornos",
	"value": "valor",
	"values": "valores",
	"type": "tipo",
	"types": "tipos",
	"instance": "instância",
	"instances": "instâncias",
	"object": "objeto",
	"objects": "objetos",
	"attribute": "atributo",
	"attributes": "atributos",
	"property": "propriedade",
	"properties": "propriedades",
	"iterator": "iterador",
	"iterable": "iterável",
	"list": "lista",
	"lists": "listas",
	"tuple": "tupla",
	"tuples": "tuplas",
	"dict": "dicionário",
	"dictionary": "dicionário",
	"set": "conjunto",
	"sets": "conjuntos",
	"string": "string",
	"strings": "strings",
	"bytes": "bytes",
	"bool": "booleano",
	"boolean": "booleano",
	"int": "inteiro",
	"float": "ponto flutuante",

	"git": "git",
	"repository": "repositório",
	"repositories": "repositórios",
	"branch": "branch",
	"branches": "branches",
	"tag": "tag",
	"tags": "tags",
	"commits": "commits",
	"merge": "merge",
	"rebase": "rebase",
	"pull": "pull",
	"push": "push",
	"fetch": "fetch",
	"clone": "clonar",
	"origin": "origin",
	"remote": "remoto",
	"stash": "stash",
	"staged": "preparado",
	"conflict": "conflito",
	"conflicts": "conflitos",
	"diff": "diff",
	"history": "histórico",

	"docker": "docker",
	"container": "contêiner",
	"containers": "contêineres",
	"image": "imagem",
	"images": "imagens",
	"volume": "volume",
	"network": "rede",
	"compose": "compose",
	"daemon": "daemon",
	"tagged": "tagueado",
	"built": "construído",
	"run": "executar",
	"exec": "exec",
	"attach": "anexar",
	"detach": "desanexar",
	"inspect": "inspecionar",

	"database": "banco de dados",
	"databases": "bancos de dados",
	"table": "tabela",
	"tables": "tabelas",
	"row": "linha",
	"rows": "linhas",
	"columns": "colunas",
	"record": "registro",
	"records": "registros",
	"index": "índice",
	"indexes": "índices",
	"query": "consulta",
	"queries": "consultas",
	"transaction": "transação",
	"transactions": "transações",
	"commit": "commit",
	"rollback": "rollback",
	"schema": "esquema",
	"schemas": "esquemas",
	"constraint": "restrição",
	"constraints": "restrições",
	"cursor": "cursor",
	"connection pool": "pool de conexões",
		"crash": "travamento",
		"crashed": "travou",
		"hang": "congelar",
		"hanged": "congelado",
		"freeze": "congelar",
		"frozen": "congelado",
		"bug": "bug",
		"bugs": "bugs",
		"issue": "problema",
		"issues": "problemas",
		"problem": "problema",
		"problems": "problemas",
		"fix": "corrigir",
		"fixed": "corrigido",
		"patched": "corrigido",
		"workaround": "solução alternativa",
		"debugging": "depuração",
		"trace": "rastro",
		"traceback": "rastreamento",
		"frame": "quadro",
		"frames": "quadros",
		"line": "linha",
		"lines": "linhas",
		"column": "coluna",
		"offset": "deslocamento",
		"source": "fonte",
		"source code": "código-fonte",

		"compile": "compilar",
		"compiled": "compilado",
		"compiler": "compilador",
		"interpreted": "interpretado",
		"interpreter": "interpretador",
		"runtime": "tempo de execução",
		"build": "compilação",
		"optimize": "otimizar",
		"optimized": "otimizado",
		"optimization": "otimização",
		"flag": "flag",
		"flags": "flags",
		"option": "opção",
		"options": "opções",
		"argument list": "lista de argumentos",

		"syntax": "sintaxe",
		"semantic": "semântica",
		"semantics": "semântica",
		"token": "token",
		"tokens": "tokens",
		"parser": "parser",
		"parse": "analisar",
		"parsed": "analisado",
		"grammar": "gramática",
		"rule": "regra",
		"rules": "regras",

		"loop": "laço",
		"loops": "laços",
		"for": "for",
		"while": "while",
		"if": "if",
		"else": "else",
		"elif": "elif",
		"match": "match",
		"case": "caso",
		"switch": "switch",
		"break": "break",
		"continue": "continue",
		"return": "return",
		"yield": "yield",
		"await": "await",
		"async": "assíncrono",
		"sync": "síncrono",

		"true": "verdadeiro",
		"false": "falso",
		"none": "nenhum",
		"null": "nulo",
		"undefined": "indefinido",
		"default value": "valor padrão",

		"overflow": "estouro",
		"underflow": "subfluxo",
		"divide": "dividir",
		"division": "divisão",
		"zero": "zero",
		"nan": "nan",
		"infinity": "infinito",

		"path separator": "separador de caminho",
		"newline": "quebra de linha",
		"whitespace": "espaço em branco",
		"tab": "tabulação",
		"space": "espaço",
		"spaces": "espaços",
		"indent": "indentar",
		"indentation": "indentação",
		"unindent": "desindentar",

		"config": "configuração",
		"configs": "configurações",
		"configuration": "configuração",
		"settings": "configurações",
		"option file": "arquivo de opções",
		"config file": "arquivo de configuração",
		"env": "ambiente",
		".env file": "arquivo .env",

		"log": "log",
		"logs": "logs",
		"logging": "registro de logs",
		"level": "nível",
		"levels": "níveis",
		"verbose": "verboso",
		"verbosity": "verbosidade",
		"trace level": "nível de rastreamento",
		"info": "informação",
		"debug level": "nível de depuração",
		"error level": "nível de erro",

		"queue": "fila",
		"queues": "filas",
		"stack": "pilha",
		"heap": "heap",
		"buffer": "buffer",
		"buffers": "buffers",
		"cache": "cache",
		"cached": "em cache",
		"hit": "acerto",
		"miss": "falha",

		"thread-safe": "seguro para threads",
		"unsafe": "inseguro",
		"race": "condição de corrida",
		"deadlock": "deadlock",
		"lock": "bloqueio",
		"locks": "bloqueios",
		"mutex": "mutex",
		"semaphore": "semáforo",

		"timeout value": "valor de tempo limite",
		"retry count": "número de tentativas",
		"interval": "intervalo",
		"delay": "atraso",
		"schedule": "agendar",
		"scheduled": "agendado",
		"job": "tarefa",
		"jobs": "tarefas",
		"task": "tarefa",
		"tasks": "tarefas",
		"worker": "worker",
		"workers": "workers",

		"host key": "chave do host",
		"public key": "chave pública",
		"private key": "chave privada",
		"fingerprint": "impressão digital",
		"cipher": "cifra",
		"algorithm": "algoritmo",
		"algorithms": "algoritmos",
		"hash": "hash",
		"hashed": "com hash",
		"salt": "sal",
		"iv": "vetor de inicialização",

		"session id": "id de sessão",
		"request id": "id de requisição",
		"transaction id": "id de transação",
		"trace id": "id de rastreamento",

		"http": "http",
		"https": "https",
		"method": "método",
		"methods": "métodos",
		"get": "get",
		"post": "post",
		"put": "put",
		"delete": "delete",
		"patch": "patch",
		"head": "head",
		"options method": "método options",
		"status code": "código de status",
		"headers": "cabeçalhos",
		"header": "cabeçalho",
		"body": "corpo",
		"payload": "payload",
		"cookie": "cookie",
		"cookies": "cookies",
		"session cookie": "cookie de sessão",

		"json": "json",
		"xml": "xml",
		"yaml": "yaml",
		"toml": "toml",
		"csv": "csv",
		"binary": "binário",
		"text": "texto",
		"format": "formato",
		"compressed": "comprimido",
		"uncompressed": "descomprimido",
		"archive": "arquivo compactado",
		"tar": "tar",
		"zip": "zip",
		"gzip": "gzip",
		"bzip2": "bzip2",

		"cli": "linha de comando",
		"shell": "shell",
		"terminal": "terminal",
		"console": "console",
		"prompt": "prompt",
		"command": "comando",
		"commands": "comandos",
		"script file": "arquivo de script",
		"stdout": "stdout",
		"stderr": "stderr",
		"stdin": "stdin",
		"pipe": "pipe",
		"piped": "encadeado",
		"exit code": "código de saída",
		"exit status": "status de saída",

		"linux": "linux",
		"windows": "windows",
		"macos": "macos",
		"unix": "unix",
		"distribution": "distribuição",
		"kernel version": "versão do kernel",
		"shell script": "script de shell",
		"batch file": "arquivo em lote",
		"service manager": "gerenciador de serviços",

		"host name": "nome do host",
		"hostname": "hostname",
		"fqdn": "nome de domínio completo",
		"subdomain": "subdomínio",
		"top-level domain": "domínio de topo",

		"cluster": "cluster",
		"node": "nó",
		"nodes": "nós",
		"master": "mestre",
		"worker node": "nó de trabalho",
		"leader": "líder",
		"follower": "seguidor",

		"queue length": "tamanho da fila",
		"load": "carga",
		"uptime": "tempo de atividade",
		"downtime": "tempo de inatividade",
		"health check": "verificação de saúde",
		"healthy": "saudável",
		"unhealthy": "não saudável",

		"role": "papel",
		"roles": "papéis",
		"policy": "política",
		"policies": "políticas",
		"scope": "escopo",
		"scopes": "escopos",

		"snapshot": "snapshot",
		"backup": "backup",
		"restore": "restaurar",
		"restored": "restaurado",

		"metrics": "métricas",
		"monitoring": "monitoramento",
		"alert": "alerta",
		"alerts": "alertas",
		"threshold": "limite",
		"thresholds": "limites",

		"schema migration": "migração de esquema",
		"migration": "migração",
		"migrations": "migrações",
		"seed": "seed",
		"seeding": "semeando",

		"orphan": "órfão",
		"stale": "obsoleto",
		"deprecated": "obsoleto",
		"legacy": "legado",
		"modern": "moderno",

		"hook": "gancho",
		"hooks": "ganchos",
		"callback": "callback",
		"callbacks": "callbacks",
		"handler": "handler",
		"handlers": "handlers",
		"middleware": "middleware",

		"queue worker": "worker de fila",
		"job queue": "fila de tarefas",
		"background": "plano de fundo",
		"foreground": "primeiro plano",

		"interactive": "interativo",
		"non-interactive": "não interativo",
		"batch": "lote",

		"start": "iniciar",
		"stop": "parar",
		"restart": "reiniciar",
		"reload": "recarregar",
		"restarted": "reiniciado",
		"reloaded": "recarregado",

		"alias": "apelido",
		"shortcut": "atalho",

		"orphaned process": "processo órfão",
		"zombie process": "processo zumbi",

		"priority": "prioridade",
		"priorities": "prioridades",

		"min": "mínimo",
		"max": "máximo",
		"average": "média",
		"median": "mediana",

		"sample": "amostra",
		"samples": "amostras",

		"pool": "pool",
		"pools": "pools",

		"retry policy": "política de novas tentativas",
	"pip": "pip",
	"npm": "npm",
	"package manager": "gerenciador de pacotes",
	"install": "instalar",
	"installed": "instalado",
	"uninstall": "desinstalar",
	"uninstalled": "desinstalado",
	"update": "atualizar",
	"upgrade": "atualizar",
	"downgrade": "reverter versão",
		"allocator": "alocador",
		"allocation": "alocação",
		"allocated": "alocado",
		"deallocated": "desalocado",
		"leak": "vazamento",
		"memory leak": "vazamento de memória",
		"profile": "perfil",
		"profiling": "perfilamento",
		"sampler": "amostrador",

		"event": "evento",
		"events": "eventos",
		"listener": "ouvinte",
		"listeners": "ouvintes",
		"subscriber": "assinante",
		"publish": "publicar",
		"publisher": "publicador",
		"subscribe": "assinar",
		"unsubscribe": "cancelar assinatura",
		"queue name": "nome da fila",
		"topic": "tópico",
		"topics": "tópicos",

		"retry delay": "atraso entre tentativas",
		"backoff": "retrocesso",
		"exponential backoff": "retrocesso exponencial",

		"ipv4": "ipv4",
		"ipv6": "ipv6",
		"subnet": "sub-rede",
		"subnet mask": "máscara de sub-rede",
		"cidr": "cidr",
		"mac address": "endereço mac",

		"stdin redirection": "redirecionamento de stdin",
		"stdout redirection": "redirecionamento de stdout",
		"stderr redirection": "redirecionamento de stderr",
		"here document": "here document",

		"orphaned resource": "recurso órfão",
		"cleanup": "limpeza",
		"garbage collector": "coletor de lixo",
		"finalizer": "finalizador",

		"namespace": "namespace",
		"namespaces": "namespaces",
		"scope leak": "vazamento de escopo",

		"bootstrap": "bootstrap",
		"bootstrapper": "inicializador",
		"initializer": "inicializador",

		"lifecycle": "ciclo de vida",
		"startup": "inicialização",
		"shutdown": "desligamento",

		"security": "segurança",
		"vulnerability": "vulnerabilidade",
		"vulnerabilities": "vulnerabilidades",
		"exploit": "exploit",
		"attack": "ataque",
		"attacker": "atacante",
		"defender": "defensor",
		"authorization": "autorização",
		"authentication": "autenticação",
		"confidentiality": "confidencialidade",
		"integrity": "integridade",
		"availability": "disponibilidade",
		"audit": "auditoria",
		"auditing": "auditoria",
		"compliance": "conformidade",

		"role-based access control": "controle de acesso baseado em papéis",
		"access control list": "lista de controle de acesso",

		"sql": "sql",
		"nosql": "nosql",
		"query plan": "plano de consulta",
		"optimizer": "otimizador",
		"index scan": "varredura de índice",
		"table scan": "varredura de tabela",
		"lock wait": "espera de bloqueio",

		"hot standby": "standby quente",
		"replica": "réplica",
		"replication": "replicação",
		"primary": "primário",
		"secondary": "secundário",

		"leader election": "eleição de líder",
		"consensus": "consenso",
		"quorum": "quórum",

		"blob": "blob",
		"object storage": "armazenamento de objetos",
		"filesystem": "sistema de arquivos",

		"pagination": "paginação",
		"offset pagination": "paginação por deslocamento",
		"cursor pagination": "paginação por cursor",

		"throttling": "restrição de taxa",
		"rate limit": "limite de taxa",

		"cache key": "chave de cache",
		"cache entry": "entrada de cache",
		"cache size": "tamanho do cache",

		"api": "api",
		"endpoint": "endpoint",
		"endpoints": "endpoints",
		"versioning": "versionamento",

		"schema validation": "validação de esquema",
		"validator": "validador",
		"validation": "validação",

		"serializer": "serializador",
		"deserializer": "desserializador",

		"middleware stack": "pilha de middleware",

		"job id": "id da tarefa",
		"task id": "id da tarefa",

		"cron": "cron",
		"cron job": "tarefa cron",
		"schedule expression": "expressão de agendamento",

		"kernel panic": "pânico do kernel",
		"panic": "pânico",

		"cgroup": "cgroup",
		"namespace isolation": "isolamento de namespace",

		"dockerfile": "dockerfile",
		"entrypoint": "entrypoint",
		"healthcheck": "verificação de saúde",
		"bind mount": "montagem vinculada",
		"overlay": "overlay",

		"image id": "id da imagem",
		"container id": "id do contêiner",
		"layer": "camada",
		"layers": "camadas",

		"bridge network": "rede bridge",
		"overlay network": "rede overlay",

		"git hook": "gancho do git",
		"pre-commit": "pre-commit",
		"pre-push": "pre-push",
		"post-merge": "post-merge",

		"remote url": "url remota",
		"upstream": "upstream",
		"origin url": "url do origin",

		"stash pop": "stash pop",
		"stash apply": "stash apply",

		"reflog": "reflog",
		"HEAD": "HEAD",

		"tag name": "nome da tag",
		"branch name": "nome da branch",

		"fast-forward": "fast-forward",

		"bare repository": "repositório nu",

		"venv path": "caminho do venv",
		"site-packages": "site-packages",

		"requirements file": "arquivo de requisitos",

		"pip cache": "cache do pip",
		"wheel": "wheel",
		"source distribution": "distribuição de código-fonte",

		"lock file": "arquivo de bloqueio",
		"package.json": "package.json",
		"package-lock.json": "package-lock.json",
		"node_modules": "node_modules",

		"linter": "linter",
		"formatter": "formatador",
		"static analysis": "análise estática",

		"type checker": "verificador de tipos",
		"mypy": "mypy",
		"flake8": "flake8",
		"pylint": "pylint",
		"black": "black",

		"coverage": "cobertura",
		"unit test": "teste unitário",
		"integration test": "teste de integração",
		"test suite": "suíte de testes",
		"test runner": "executor de testes",

		"assertion": "assertiva",
		"assert": "assert",

		"fixture": "fixture",

		"event loop": "loop de eventos",
		"future": "future",
		"promise": "promise",

		"main thread": "thread principal",
		"worker thread": "thread de trabalho",

		"critical section": "seção crítica",

		"hot reload": "recarga a quente",
		"hot restart": "reinício a quente",

		"websocket": "websocket",
		"handshake timeout": "tempo limite do handshake",
		"frame size": "tamanho do quadro",

		"csrf": "csrf",
		"xss": "xss",
		"sqli": "injeção sql",
		"open redirect": "redirecionamento aberto",

		"csrf token": "token csrf",

		"ip whitelist": "lista branca de ip",
		"ip blacklist": "lista negra de ip",
		"allowlist": "lista de permitidos",
		"denylist": "lista de negados",

		"session store": "armazenamento de sessão",

		"load balancer": "balanceador de carga",
		"backend": "backend",
		"frontend": "frontend",
		"upstream server": "servidor upstream",
		"health probe": "sonda de saúde",

		"request queue": "fila de requisições",

		"circuit breaker": "disjuntor",
		"fallback": "alternativa",
		"bulkhead": "compartimento",

		"trace span": "span de rastreamento",
		"span": "span",

		"observability": "observabilidade",
		"telemetry": "telemetria",

		"metric": "métrica",
		"counter": "contador",
		"gauge": "medidor",
		"histogram": "histograma",

		"dashboard": "painel",
		"panel": "painel",

		"namespace conflict": "conflito de namespace",

		"override": "sobrescrever",
		"overridden value": "valor sobrescrito",

		"feature flag": "flag de funcionalidade",

		"rollback plan": "plano de rollback",
		"deployment": "implantação",
		"deploy": "implantar",
		"release": "release",
		"canary": "canário",
		"blue-green": "blue-green",

		"maintenance": "manutenção",
		"maintenance window": "janela de manutenção",

		"hotfix": "hotfix",
		"bugfix": "correção de bug",

		"changelog": "changelog",

		"semantic versioning": "versionamento semântico",
		"major": "maior",
		"minor": "menor",
		"patch level": "nível de patch",

		"artifact": "artefato",
		"artifact repository": "repositório de artefatos",

		"ci": "ci",
		"cd": "cd",
		"pipeline": "pipeline",
		"stage": "estágio",
		"job step": "etapa de tarefa",

		"runner": "runner",
		"agent": "agente",

		"workspace": "workspace",
		"working directory": "diretório de trabalho",

		"checkout": "checkout",

		"environment variable": "variável de ambiente",
		"secret": "segredo",
		"secrets": "segredos",

		"mask": "mascarar",
		"masked": "mascarado",

		"retry strategy": "estratégia de novas tentativas",

		"quota": "cota",
		"hard limit": "limite rígido",
		"soft limit": "limite flexível",

		"session timeout": "tempo limite de sessão",

		"keepalive": "keepalive",

		"ping": "ping",
		"pong": "pong",

		"round-trip time": "tempo de ida e volta",

		"dns cache": "cache de dns",
		"resolver": "resolvedor",

		"trust store": "repositório de confiança",
		"key store": "repositório de chaves",

		"tls version": "versão de tls",
		"cipher suite": "conjunto de cifras",

		"handshake failure": "falha no handshake",

		"loopback": "loopback",

		"gateway timeout": "tempo limite do gateway",

		"service discovery": "descoberta de serviços",

		"http proxy": "proxy http",
		"https proxy": "proxy https",

		"upstream timeout": "tempo limite do upstream",

		"body size": "tamanho do corpo",
		"header size": "tamanho do cabeçalho",

		"idle connection": "conexão ociosa",

		"prefetch": "pré-busca",
		"preload": "pré-carregar",

		"warmup": "aquecimento",

		"rolling update": "atualização gradual",

		"replica count": "número de réplicas",

		"pod": "pod",
		"namespace (k8s)": "namespace (k8s)",
		"cluster ip": "ip de cluster",
		"node port": "porta de nó",
		"ingress": "ingress",
		"egress": "egress",

		"service account": "conta de serviço",

		"config map": "config map",
		"secret mount": "montagem de segredo",

		"readiness probe": "sonda de prontidão",
		"liveness probe": "sonda de vida",

		"init container": "contêiner de inicialização",

		"sidecar": "sidecar",	"dependency": "dependência",
	"dependencies": "dependências",
	"version": "versão",
	"versions": "versões",
	"lockfile": "arquivo de bloqueio",
	"registry": "registro",
	"global": "global",
	"local": "local",
	"virtualenv": "ambiente virtual",
	"venv": "venv",
		 "ERROR: unknown command": "ERRO: comando desconhecido",
    "maybe you meant": "talvez você quis dizer",
    "Package": "Pacote",
    "Version": "Versão",
    "Successfully installed": "Instalado com sucesso",
    "Requirement already satisfied": "Dependência já satisfeita",
    "Installing": "Instalando",
    "Uninstalling": "Desinstalando",
    "Updating": "Atualizando",
    "Up-to-date": "Atualizado",
    "Dependency": "Dependência",
    "Module": "Módulo",
    "Command": "Comando",
    "Not recognized": "Não reconhecido",
    "File": "Arquivo",
    "Directory": "Diretório",
    "Permission denied": "Permissão negada",
    "Access denied": "Acesso negado",
    "The term": "O termo",
    "is not recognized": "não é reconhecido",
    "Cannot find path": "Não foi possível encontrar o caminho",
    "Traceback": "Rastreamento de erro",
    "Exception": "Exceção",
    "SyntaxError": "Erro de sintaxe",
    "IndentationError": "Erro de indentação",
    "NameError": "Erro de nome",
    "ImportError": "Erro de importação",
    "ModuleNotFoundError": "Módulo não encontrado",
		"Operation not permitted": "Operação não permitida",
		"Connection refused": "Conexão recusada",
		"Command not found": "Comando não encontrado",
		"No such file or directory": "Arquivo ou diretório inexistente",
		"Operation timed out": "Operação expirou",
		"Invalid argument": "Argumento inválido",
		"Segmentation fault": "Falha de segmentação",
		"Broken pipe": "Pipe quebrado",
		"Read-only file system": "Sistema de arquivos somente leitura",
		"Out of memory": "Memória insuficiente",
		"Device or resource busy": "Dispositivo ou recurso ocupado",
		"Network is unreachable": "Rede inacessível",
		"Connection timed out": "Conexão expirada",
		"Host unreachable": "Host inacessível",
		"Permission error": "Erro de permissão",
		"Unknown error": "Erro desconhecido",
		"Invalid option": "Opção inválida",
		"Invalid command": "Comando inválido",
		"Invalid input": "Entrada inválida",
		"Invalid syntax": "Sintaxe inválida",
		"Invalid path": "Caminho inválido",
		"Path not found": "Caminho não encontrado",
		"Disk full": "Disco cheio",
		"No space left on device": "Sem espaço disponível no dispositivo",
		"Device not ready": "Dispositivo não está pronto",
		"Access is denied": "Acesso negado",
		"Operation aborted": "Operação abortada",
		"Operation failed": "Operação falhou",
		"Operation successful": "Operação bem-sucedida",
		"Unknown host": "Host desconhecido",
		"Connection closed": "Conexão encerrada",
		"Connection reset": "Conexão redefinida",
		"Connection aborted": "Conexão abortada",
		"Network error": "Erro de rede",
		"Network timeout": "Tempo de rede esgotado",
		"Authentication failed": "Autenticação falhou",
		"Login failed": "Falha no login",
		"User not found": "Usuário não encontrado",
		"Access forbidden": "Acesso proibido",
		"Resource temporarily unavailable": "Recurso temporariamente indisponível",
		"Service unavailable": "Serviço indisponível",
		"Internal server error": "Erro interno do servidor",
		"Bad request": "Requisição inválida",
		"Request timed out": "Requisição expirou",
		"Host not found": "Host não encontrado",
		"Name or service not known": "Nome ou serviço desconhecido",
		"Address already in use": "Endereço já em uso",
		"Connection in progress": "Conexão em andamento",
		"Protocol error": "Erro de protocolo",
		"Broken connection": "Conexão quebrada",
		"File not found": "Arquivo não encontrado",
		"File exists": "Arquivo já existe",
		"File is busy": "Arquivo está ocupado",
		"File is read-only": "Arquivo é somente leitura",
		"Cannot open file": "Não foi possível abrir o arquivo",
		"Cannot write file": "Não foi possível escrever no arquivo",
		"Cannot read file": "Não foi possível ler o arquivo",
		"Directory not empty": "Diretório não está vazio",
		"Invalid file descriptor": "Descritor de arquivo inválido",
		"End of file": "Fim de arquivo",
		"Corrupted file": "Arquivo corrompido",
		"File too large": "Arquivo muito grande",
		"Path too long": "Caminho muito longo",
		"Device not found": "Dispositivo não encontrado",
		"Device error": "Erro no dispositivo",
		"Resource not found": "Recurso não encontrado",
		"Resource already exists": "Recurso já existe",
		"Resource busy": "Recurso ocupado",
		"Resource locked": "Recurso bloqueado",
		"Lock timeout": "Tempo de bloqueio expirado",
		"Configuration error": "Erro de configuração",
		"Invalid configuration": "Configuração inválida",
		"Missing configuration": "Configuração ausente",
		"Environment variable not set": "Variável de ambiente não definida",
		"Invalid environment": "Ambiente inválido",
		"Dependency not found": "Dependência não encontrada",
		"Unsupported operation": "Operação não suportada",
		"Unsupported option": "Opção não suportada",
		"Feature not implemented": "Funcionalidade não implementada",
		"Not implemented": "Não implementado",
		"Not supported": "Não suportado",
		"Function not available": "Função não disponível",
		"Service not available": "Serviço não disponível",
		"Service not responding": "Serviço não está respondendo",
		"Timeout exceeded": "Tempo limite excedido",
		"Request failed": "Requisição falhou",
		"Invalid response": "Resposta inválida",
		"Unexpected response": "Resposta inesperada",
		"Protocol not supported": "Protocolo não suportado",
		"Version not supported": "Versão não suportada",
		"Invalid version": "Versão inválida",
		"Checksum error": "Erro de checksum",
		"Data corrupted": "Dados corrompidos",
		"Invalid data": "Dados inválidos",
		"Missing data": "Dados ausentes",
		"Incomplete data": "Dados incompletos",
		"Parsing error": "Erro de parsing",
		"JSON decode error": "Erro ao decodificar JSON",
		"JSON encode error": "Erro ao codificar JSON",
		"XML parse error": "Erro ao analisar XML",
		"YAML parse error": "Erro ao analisar YAML",
		"Invalid format": "Formato inválido",
		"Unsupported format": "Formato não suportado",
		"Compilation error": "Erro de compilação",
		"Compilation failed": "Compilação falhou",
		"Build failed": "Build falhou",
		"Build successful": "Build bem-sucedido",
		"Runtime error": "Erro em tempo de execução",
		"Logical error": "Erro lógico",
		"TypeError": "Erro de tipo",
		"ValueError": "Erro de valor",
		"IndexError": "Erro de índice",
		"KeyError": "Erro de chave",
		"AttributeError": "Erro de atributo",
		"ZeroDivisionError": "Erro de divisão por zero",
		"OverflowError": "Erro de estouro aritmético",
		"RuntimeWarning": "Aviso de tempo de execução",
		"DeprecationWarning": "Aviso de descontinuação",
		"FutureWarning": "Aviso de mudança futura",
		"KeyboardInterrupt": "Interrupção pelo teclado",
		"SystemExit": "Saída do sistema",
		"OSError": "Erro de sistema operacional",
		"IOError": "Erro de entrada/saída",
		"MemoryError": "Erro de memória",
		"ConnectionError": "Erro de conexão",
		"TimeoutError": "Erro de tempo limite",
		"FileNotFoundError": "Arquivo não encontrado",
		"PermissionError": "Erro de permissão",
		"Process exited with code": "Processo finalizado com código",
		"Process terminated": "Processo encerrado",
		"Process killed": "Processo morto",
		"Illegal instruction": "Instrução ilegal",
		"Abort trap": "Interrupção de aborto",
		"Bad file descriptor": "Descritor de arquivo inválido",
		"Too many open files": "Excesso de arquivos abertos",
		"Argument list too long": "Lista de argumentos muito longa",
		"Operation not supported": "Operação não suportada",
		"Socket error": "Erro de socket",
		"Socket closed": "Socket fechado",
		"Port already in use": "Porta já em uso",
		"Unreachable code": "Código inacessível",
		"Unhandled exception": "Exceção não tratada",
		"Unhandled error": "Erro não tratado",
		"Initialization failed": "Falha na inicialização",
		"Initialization error": "Erro de inicialização",
		"Shutdown failed": "Falha no desligamento",
		"Cleanup failed": "Falha na limpeza",
		"Invalid state": "Estado inválido",
		"Unexpected state": "Estado inesperado",
		"Concurrency error": "Erro de concorrência",
		"Deadlock detected": "Deadlock detectado",
		"Race condition": "Condição de corrida",
		"Thread error": "Erro de thread",
		"Process error": "Erro de processo",
		"Lock error": "Erro de bloqueio",
		"Database error": "Erro de banco de dados",
		"Database locked": "Banco de dados bloqueado",
		"Database busy": "Banco de dados ocupado",
		"Transaction failed": "Transação falhou",
		"Transaction aborted": "Transação abortada",
		"Commit failed": "Commit falhou",
		"Rollback failed": "Rollback falhou",
		"Query failed": "Consulta falhou",
		"Syntax error in SQL": "Erro de sintaxe em SQL",
		"Constraint violation": "Violação de restrição",
		"Duplicate key": "Chave duplicada",
		"Record not found": "Registro não encontrado",
		"Invalid credentials": "Credenciais inválidas",
		"Token expired": "Token expirado",
		"Token invalid": "Token inválido",
		"Session expired": "Sessão expirada",
		"Session not found": "Sessão não encontrada",
		"Access token required": "Token de acesso necessário",
		"Insufficient privileges": "Privilégios insuficientes",
		"Rate limit exceeded": "Limite de requisições excedido",
		"Quota exceeded": "Cota excedida",
		"API key missing": "Chave de API ausente",
		"API key invalid": "Chave de API inválida",
		"API error": "Erro de API",
		"Service error": "Erro de serviço",
		"Cache miss": "Falha no cache",
		"Cache error": "Erro de cache",
		"Timeout while waiting for lock": "Tempo limite ao aguardar bloqueio",
		"Timeout while waiting for response": "Tempo limite ao aguardar resposta",
		"Failed to connect": "Falha ao conectar",
		"Failed to bind": "Falha ao vincular",
		"Failed to listen": "Falha ao escutar",
		"Failed to accept connection": "Falha ao aceitar conexão",
		"Failed to send data": "Falha ao enviar dados",
		"Failed to receive data": "Falha ao receber dados",
		"Host is down": "Host está inativo",
		"Server is down": "Servidor está inativo",
		"Client error": "Erro do cliente",
		"Server error": "Erro do servidor",
		"Unknown command": "Comando desconhecido",
		"Missing argument": "Argumento ausente",
		"Too many arguments": "Argumentos em excesso",
		"Option requires an argument": "A opção requer um argumento",
		"Invalid flag": "Flag inválida",
		"Unknown option": "Opção desconhecida",
		"Command aborted": "Comando abortado",
		"Command failed": "Comando falhou",
		"Command executed successfully": "Comando executado com sucesso",
		"Nothing to do": "Nada a fazer",
		"Already up to date": "Já está atualizado",
		"Change rejected": "Alteração rejeitada",
		"Operation cancelled by user": "Operação cancelada pelo usuário",
		"Read error": "Erro de leitura",
		"Write error": "Erro de escrita",
		"Permission required": "Permissão necessária",
		"Administrator privileges required": "Privilégios de administrador necessários",
		"Root privileges required": "Privilégios de root necessários",
		"Invalid user": "Usuário inválido",
		"Invalid password": "Senha inválida",
		"Password required": "Senha necessária",
		"Disk error": "Erro de disco",
		"I/O error": "Erro de E/S",
		"Mount failed": "Falha ao montar",
		"Unmount failed": "Falha ao desmontar",
		"Invalid mount point": "Ponto de montagem inválido",
		"Read-only mount": "Montagem somente leitura",
		"Access violation": "Violação de acesso",
		"Segmentation violation": "Violação de segmentação",
		"Bus error": "Erro de barramento",
		"Stack overflow": "Estouro de pilha",
		"Stack underflow": "Subutilização de pilha",
		"Heap corruption": "Corrupção de heap",
		"Garbage collection error": "Erro de coleta de lixo",
		"Out of disk space": "Sem espaço em disco",
		"Low memory warning": "Aviso de pouca memória",
		"Deprecated option": "Opção obsoleta",
		"Deprecated feature": "Funcionalidade obsoleta",
		"Invalid locale": "Configuração regional inválida",
		"Encoding error": "Erro de codificação",
		"Decoding error": "Erro de decodificação",
		"Unicode error": "Erro de Unicode",
		"Invalid character": "Caractere inválido",
		"Unsupported character set": "Conjunto de caracteres não suportado",
		"Time synchronization error": "Erro de sincronização de tempo",
		"Clock skew detected": "Diferença de relógio detectada",
		"Invalid timestamp": "Carimbo de tempo inválido",
		"Timeout while acquiring lock": "Tempo limite ao adquirir bloqueio",
		"Resource initialization failed": "Falha na inicialização do recurso",
		"Resource cleanup failed": "Falha na limpeza do recurso",
		"Module load error": "Erro ao carregar módulo",
		"Module unload error": "Erro ao descarregar módulo",
		"Plugin load error": "Erro ao carregar plugin",
		"Plugin not found": "Plugin não encontrado",
		"Extension not found": "Extensão não encontrada",
		"Unsupported platform": "Plataforma não suportada",
		"Incorrect platform": "Plataforma incorreta",
		"Unsupported architecture": "Arquitetura não suportada",
		"Missing dependency": "Dependência ausente",
		"Circular dependency detected": "Dependência circular detectada",
		"Version conflict": "Conflito de versão",
		"Lock file exists": "Arquivo de bloqueio existente",
		"Corrupted lock file": "Arquivo de bloqueio corrompido",
		"Invalid license": "Licença inválida",
		"License expired": "Licença expirada",
		"License not found": "Licença não encontrada",
		"Security error": "Erro de segurança",
		"Encryption error": "Erro de criptografia",
		"Decryption error": "Erro de descriptografia",
		"Certificate error": "Erro de certificado",
		"Certificate expired": "Certificado expirado",
		"Certificate revoked": "Certificado revogado",
		"Handshake failed": "Handshake falhou",
		"SSL error": "Erro de SSL",
		"TLS error": "Erro de TLS",
		"Secure connection failed": "Conexão segura falhou",
		"Invalid signature": "Assinatura inválida",
		"Integrity check failed": "Verificação de integridade falhou",
		"Sandbox violation": "Violação de sandbox",
		"Forbidden operation": "Operação proibida",
		"Resource limit exceeded": "Limite de recurso excedido",
		"CPU limit exceeded": "Limite de CPU excedido",
		"Memory limit exceeded": "Limite de memória excedido",
		"File size limit exceeded": "Limite de tamanho de arquivo excedido",
		"Too many requests": "Requisições em excesso",
		"Too many connections": "Conexões em excesso",
		"Pool exhausted": "Pool esgotado",
		"Queue full": "Fila cheia",
		"Queue empty": "Fila vazia",
		"Job failed": "Tarefa falhou",
		"Job cancelled": "Tarefa cancelada",
		"Task failed": "Tarefa falhou",
		"Task cancelled": "Tarefa cancelada",
		"Scheduler error": "Erro do agendador",
		"Configuration file not found": "Arquivo de configuração não encontrado",
		"Configuration file invalid": "Arquivo de configuração inválido",
		"Log file not found": "Arquivo de log não encontrado",
		"Cannot write log file": "Não foi possível escrever o arquivo de log",
		"Debug mode enabled": "Modo de depuração ativado",
		"Debug mode disabled": "Modo de depuração desativado",
		"Insufficient storage": "Armazenamento insuficiente",
		"Unknown signal": "Sinal desconhecido",
		"Signal received": "Sinal recebido",
		"Interrupted system call": "Chamada de sistema interrompida",
		"Child process failed": "Processo filho falhou",
		"Child process exited abnormally": "Processo filho finalizou de forma anormal",
		"Broken link": "Link quebrado",
		"Symbolic link error": "Erro em link simbólico",
		"Invalid pointer": "Ponteiro inválido",
		"Null pointer": "Ponteiro nulo",
		"Out of range": "Fora do intervalo",
		"Index out of range": "Índice fora do intervalo",
		"Port not open": "Porta não está aberta",
		"Interface not found": "Interface não encontrada",
		"Invalid interface": "Interface inválida",
		"Hardware error": "Erro de hardware",
		"Firmware error": "Erro de firmware",
		"Driver error": "Erro de driver",
		"Update failed": "Atualização falhou",
		"Download failed": "Download falhou",
		"Upload failed": "Upload falhou",
		"Checksum mismatch": "Inconsistência de checksum",
		"Signature mismatch": "Inconsistência de assinatura",
		"Command not allowed": "Comando não permitido",
		"Read timeout": "Tempo limite de leitura",
		"Write timeout": "Tempo limite de escrita",
		"Connection already exists": "Conexão já existe",
		"Session already exists": "Sessão já existe",
		"Invalid session": "Sessão inválida",
		"Profile not found": "Perfil não encontrado",
		"Profile corrupted": "Perfil corrompido",
		"Insufficient bandwidth": "Largura de banda insuficiente",
		"Media error": "Erro de mídia",
		"Codec not supported": "Codec não suportado",
		"Format not recognized": "Formato não reconhecido",
		"Operation already in progress": "Operação já em andamento",
		"Redirection error": "Erro de redirecionamento",
		"Pipe error": "Erro de pipe",
		"Command not permitted": "Comando não permitido",
		"Temporary failure": "Falha temporária",
		"Permanent failure": "Falha permanente",
		"Unknown status": "Status desconhecido",

		"Network down": "Rede fora do ar",
		"DNS lookup failed": "Falha na resolução de DNS",
		"Unable to resolve host": "Não foi possível resolver o host",
		"Connection was forcibly closed": "Conexão foi encerrada à força",
		"Remote host closed the connection": "Host remoto fechou a conexão",
		"Connection already closed": "Conexão já está fechada",
		"SSL handshake timeout": "Tempo limite no handshake SSL",
		"TLS negotiation failed": "Negociação TLS falhou",
		"Insecure connection": "Conexão insegura",
		"Certificate validation failed": "Falha na validação do certificado",
		"Proxy authentication required": "Autenticação de proxy necessária",
		"Proxy connection failed": "Falha na conexão com o proxy",
		"Network interface down": "Interface de rede desativada",
		"Network unreachable": "Rede inalcançável",

		"Access is denied.": "Acesso negado.",
		"System error": "Erro do sistema",
		"Unknown system error": "Erro de sistema desconhecido",
		"Registry error": "Erro no registro do sistema",
		"Service not started": "Serviço não iniciado",
		"Service already running": "Serviço já em execução",
		"Unable to start service": "Não foi possível iniciar o serviço",
		"System resource exhausted": "Recurso do sistema esgotado",
		"Insufficient system resources": "Recursos do sistema insuficientes",
		"Operation requires elevation": "A operação requer elevação de privilégios",
		"File name too long": "Nome de arquivo muito longo",
		"Invalid drive": "Unidade inválida",
		"Path access denied": "Acesso ao caminho negado",
		"Sharing violation": "Violação de compartilhamento",
		"The system cannot find the file specified": "O sistema não pode encontrar o arquivo especificado",
		"The system cannot find the path specified": "O sistema não pode encontrar o caminho especificado",
		"The process cannot access the file": "O processo não pode acessar o arquivo",
		"Device is not ready": "O dispositivo não está pronto",

		"fatal error": "erro fatal",
		"warning": "aviso",
		"info": "informação",
		"debug": "depuração",
		"critical error": "erro crítico",
		"stack trace": "pilha de chamadas",
		"unhandled signal": "sinal não tratado",
		"core dumped": "core gerado",
		"invalid operation": "operação inválida",
		"illegal operation": "operação ilegal",
		"broken dependency": "dependência quebrada",
		"failed dependency": "dependência com falha",

		"Git error": "Erro do Git",
		"not a git repository": "não é um repositório Git",
		"repository not found": "repositório não encontrado",
		"remote not found": "remoto não encontrado",
		"authentication required": "autenticação necessária",
		"authentication failed for": "autenticação falhou para",
		"failed to push some refs": "falha ao enviar alguns refs",
		"non-fast-forward": "não é fast-forward",
		"merge conflict": "conflito de mesclagem",
		"conflict detected": "conflito detectado",
		"nothing to commit": "nada a cometer",
		"working tree clean": "árvore de trabalho limpa",
		"detached HEAD": "HEAD destacado",
		"branch not found": "branch não encontrado",
		"upstream branch not set": "branch remoto não configurado",
		"tag already exists": "tag já existe",
		"cannot lock ref": "não foi possível bloquear o ref",
		"could not read from remote repository": "não foi possível ler do repositório remoto",
		"error: failed to push some refs": "erro: falha ao enviar alguns refs",
		"error: failed to fetch": "erro: falha ao buscar",

		"Docker error": "Erro do Docker",
		"image not found": "imagem não encontrada",
		"no such container": "contêiner inexistente",
		"container not found": "contêiner não encontrado",
		"failed to create container": "falha ao criar contêiner",
		"failed to start container": "falha ao iniciar contêiner",
		"container already running": "contêiner já está em execução",
		"container is not running": "contêiner não está em execução",
		"port is already allocated": "porta já está alocada",
		"failed to bind port": "falha ao vincular porta",
		"network not found": "rede não encontrada",
		"volume not found": "volume não encontrado",
		"failed to mount volume": "falha ao montar volume",
		"image pull failed": "falha ao baixar imagem",
		"manifest not found": "manifesto não encontrado",
		"driver failed programming external connectivity": "driver falhou ao programar conectividade externa",
		"permission denied while trying to connect to the Docker daemon": "permissão negada ao tentar conectar ao daemon do Docker",
		"Cannot connect to the Docker daemon": "Não foi possível conectar ao daemon do Docker",

		"Database connection failed": "Falha na conexão com o banco de dados",
		"Unable to connect to database": "Não foi possível conectar ao banco de dados",
		"Database not reachable": "Banco de dados inacessível",
		"Database not available": "Banco de dados indisponível",
		"Database does not exist": "Banco de dados não existe",
		"Table not found": "Tabela não encontrada",
		"Column not found": "Coluna não encontrada",
		"Invalid column name": "Nome de coluna inválido",
		"Duplicate entry": "Entrada duplicada",
		"Duplicate record": "Registro duplicado",
		"Primary key violation": "Violação de chave primária",
		"Foreign key violation": "Violação de chave estrangeira",
		"Unique constraint violated": "Restrição de unicidade violada",
		"Check constraint violated": "Restrição de verificação violada",
		"Transaction timeout": "Tempo limite da transação",
		"Deadlock found": "Deadlock encontrado",
		"Deadlock avoided": "Deadlock evitado",
		"Connection pool exhausted": "Pool de conexões esgotado",
		"Failed to acquire connection": "Falha ao adquirir conexão",
		"Invalid query": "Consulta inválida",
		"Query timeout": "Tempo limite da consulta",
		"Query cancelled": "Consulta cancelada",
		"Syntax error near": "Erro de sintaxe próximo a",
		"Permission denied for table": "Permissão negada para a tabela",
		"Read-only transaction": "Transação somente leitura",
		"Database is locked": "Banco de dados está bloqueado",

		"pip error": "Erro do pip",
		"pip is not recognized as an internal or external command": "pip não é reconhecido como um comando interno ou externo",
		"Could not find a version that satisfies the requirement": "Não foi possível encontrar uma versão que satisfaça o requisito",
		"No matching distribution found": "Nenhuma distribuição correspondente encontrada",
		"Failed building wheel": "Falha ao construir wheel",
		"Could not install packages due to an EnvironmentError": "Não foi possível instalar os pacotes devido a um erro de ambiente",
		"Could not install packages due to an OSError": "Não foi possível instalar os pacotes devido a um OSError",
		"Error installing package": "Erro ao instalar o pacote",
		"Error uninstalling package": "Erro ao desinstalar o pacote",
		"Error resolving dependencies": "Erro ao resolver dependências",
		"Conflicting dependencies found": "Dependências conflitantes encontradas",
		"Consider using the --user option": "Considere usar a opção --user",
		"Consider using a virtual environment": "Considere usar um ambiente virtual",
		"Requirement is not a valid wheel": "A dependência não é um wheel válido",

		"npm ERR! code": "npm ERR! código",
		"npm ERR! path": "npm ERR! caminho",
		"npm ERR! errno": "npm ERR! errno",
		"npm ERR! enoent": "npm ERR! arquivo ou diretório inexistente",
		"command failed": "comando falhou",
		"command not found": "comando não encontrado",
		"peer dependency": "dependência de par (peer dependency)",
		"missing script": "script ausente",
		"ELIFECYCLE": "ELIFECYCLE",
		"EACCES": "EACCES",
		"EADDRINUSE": "EADDRINUSE",
		"ENOTFOUND": "ENOTFOUND",
		"network request failed": "requisição de rede falhou",
		"fetch failed": "falha ao buscar",
		"integrity checksum failed": "falha na verificação de integridade",

		"Python error": "Erro de Python",
		"RuntimeWarning: coroutine": "RuntimeWarning: coroutine",
		"Event loop is closed": "Loop de eventos está fechado",
		"maximum recursion depth exceeded": "profundidade máxima de recursão excedida",
		"local variable referenced before assignment": "variável local referenciada antes de atribuição",
		"cannot import name": "não é possível importar o nome",
		"circular import": "importação circular",
		"division by zero": "divisão por zero",
		"expected an indented block": "bloco indentado esperado",
		"unexpected indent": "indentação inesperada",
		"unindent does not match any outer indentation level": "desindentação não corresponde a nenhum nível externo",
		"invalid syntax": "sintaxe inválida",
		"EOL while scanning string literal": "fim de linha ao analisar literal de string",
		"unterminated string literal": "literal de string não terminada",
		"list index out of range": "índice de lista fora do intervalo",
		"tuple index out of range": "índice de tupla fora do intervalo",
		"dictionary changed size during iteration": "dicionário mudou de tamanho durante a iteração",
		"object is not iterable": "objeto não é iterável",
		"'NoneType' object is not iterable": "objeto 'NoneType' não é iterável",
		"'NoneType' object is not subscriptable": "objeto 'NoneType' não é indexável",
		"'int' object is not iterable": "objeto 'int' não é iterável",
		"'int' object is not subscriptable": "objeto 'int' não é indexável",
		"unsupported operand type": "tipo de operando não suportado",
		"expected string or bytes-like object": "esperado objeto do tipo string ou bytes",
		"must be str, not": "deve ser str, não",
		"object is not JSON serializable": "objeto não é serializável em JSON",
	}